### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by dglsparsons** [CyberShadow/TrenD#3]
The following message occurs when attempting to load the page: 

An error occured while loading the graph data (data/data.json)
parsererror: SyntaxError: Unexpected end of JSON input

**Comment by CyberShadow** [comment]
Yeah, so much data has accumulated that major browsers fail to process it.

**Comment by lbmn** [comment]
You are hurting users with cellular phones / hot-spots for whom an unexpected pointless 300MB+ download isn't free...

**Comment by CyberShadow** [comment]
Calm down, lol. The data is compressed and in reality much smaller. Your browser (Chrome I guess) shows the uncompressed size.

**Comment by dmi7ry** [comment]
Firefox:

> error: InternalError: allocation size overflow

Chrome:

> parsererror: SyntaxError: Unexpected end of JSON input
